# Generated by Django 2.2.6 on 2019-10-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
